-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 11:31:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabrica` (
  `idFabrica` INT NOT NULL AUTO_INCREMENT COMMENT 'Id autoincrementado de la fabrica',
  `nombreFabrica` VARCHAR(45) NOT NULL COMMENT 'Nombre de la fabrica',
  PRIMARY KEY (`idFabrica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_producto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT COMMENT 'Id autoincrementado del tipo de producto',
  `nombreTipoProducto` VARCHAR(45) NOT NULL COMMENT 'Nombre del tipo de producto',
  `fabricaTipoProducto` INT NOT NULL COMMENT 'Fk fabrica, id de la fabrica al que pertenece el tipo de producto',
  PRIMARY KEY (`idTipoProducto`),
  INDEX `fk_fabrica_tipoProducto_idx` (`fabricaTipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_fabrica_tipoProducto`
    FOREIGN KEY (`fabricaTipoProducto`)
    REFERENCES `mydb`.`fabrica` (`idFabrica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT 'Id autoincrementado del producto registrado',
  `nombreProducto` VARCHAR(45) NOT NULL COMMENT 'Nombre del producto registrado',
  `codigoProducto` VARCHAR(45) NOT NULL COMMENT 'Código unico del producto registrado',
  `precioProducto` INT NOT NULL COMMENT 'Precio de producto registrado',
  `fechaFabricacionProducto` DATE NOT NULL COMMENT 'Fecha de fabricación del producto registrado',
  `imagenProducto` VARCHAR(45) NULL COMMENT 'Imagen del producto',
  `tipoProducto` INT NOT NULL COMMENT 'Fk tipo_producto, id del tipo_producto al que pertenece el producto',
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `codigoProducto_UNIQUE` (`codigoProducto` ASC) VISIBLE,
  INDEX `fk_producto_tipo_idx` (`tipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_tipo`
    FOREIGN KEY (`tipoProducto`)
    REFERENCES `mydb`.`tipo_producto` (`idTipoProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Id autoincrementado del cliente registrado',
  `nombreCliente` VARCHAR(45) NOT NULL COMMENT 'Nombre del cliente, example: Exito, Alkosto, Alkomprar, La catorce',
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT COMMENT 'Id autoincrementado ',
  `productoVenta` INT NOT NULL COMMENT 'Producto que se le registro una venta, Fk producto,  id del producto que se esta registrando la venta',
  `clienteVenta` INT NOT NULL COMMENT 'Cliente quien adquiere el producto, Fk cliente, id del cliente que realizá la compra del producto',
  `cantidadProductoVenta` INT NOT NULL COMMENT 'Cantidad del producto que se vendió',
  `totalVenta` INT NOT NULL COMMENT 'Precio total de la venta, calculado (precio del producto * la cantidad del producto adquirido)',
  `observacionVenta` VARCHAR(45) NULL COMMENT 'Observaciones de la venta registrada',
  PRIMARY KEY (`idVenta`),
  INDEX `fk_producto_venta_idx` (`productoVenta` ASC) VISIBLE,
  INDEX `fk_cliente_venta_idx` (`clienteVenta` ASC) VISIBLE,
  CONSTRAINT `fk_producto_venta`
    FOREIGN KEY (`productoVenta`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cliente_venta`
    FOREIGN KEY (`clienteVenta`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
